start-at-login = true

enable-normalization-flatten-containers = false
enable-normalization-opposite-orientation-for-nested-containers = false

on-focus-changed = ['move-mouse window-lazy-center']

[mode.main.binding]

alt-shift-c = 'reload-config'

cmd-h = []     # Disable "hide application"
cmd-alt-h = [] # Disable "hide others"

[mode.resize.binding]
h = 'resize width -50'
j = 'resize height +50'
k = 'resize height -50'
l = 'resize width +50'
enter = 'mode main'
esc = 'mode main'

[gaps]
inner.horizontal = 0
inner.vertical = 0
outer.left = 0
outer.bottom = 0
outer.top = 0
outer.right = 0


[[on-window-detected]]
if.app-id = 'company.thebrowser.Browser'
check-further-callbacks = true
run = ['move-node-to-workspace 1']

[[on-window-detected]]
if.app-id = 'com.microsoft.VSCode'
check-further-callbacks = true
run = ['move-node-to-workspace 2']

[[on-window-detected]]
if.app-id = 'com.spotify.client'
check-further-callbacks = true
run = ['move-node-to-workspace 8']

[[on-window-detected]]
if.app-id = 'com.tinyspeck.slackmacgap'
check-further-callbacks = true
run = ['move-node-to-workspace 9']

[[on-window-detected]]
if.app-id = 'com.mitchellh.ghostty'
check-further-callbacks = true
run = ['move-node-to-workspace 10']
