model = "gpt-5.1-codex"
model_reasoning_effort = "medium"
[projects."/Users/magnusholtet/dev/entur/automat-app"]
trust_level = "trusted"


[mcp_servers.context7]
command = "npx"
args = ["-y", "@upstash/context7-mcp"]

[mcp_servers.chrome_devtools]
command = "npx"
args = ["chrome-devtools-mcp@latest"]

[notice]
hide_gpt5_1_migration_prompt = true
